CREATE TABLE IF NOT EXISTS `ultrasound_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `patient_name` varchar(255) NOT NULL,
  `age` int(11) NOT NULL,
  `date` date NOT NULL,
  `referred_by` varchar(255) DEFAULT NULL,
  `lmp` varchar(50) DEFAULT NULL,
  `g` varchar(10) DEFAULT NULL,
  `p` varchar(10) DEFAULT NULL,
  `uterus_measurement` varchar(50) DEFAULT NULL,
  `uterus_position` varchar(50) DEFAULT NULL,
  `uterus_abnormalities` text DEFAULT NULL,
  `endometrium_thickness` varchar(50) DEFAULT NULL,
  `endometrium_type` varchar(50) DEFAULT NULL,
  `menstrual_phase` varchar(100) DEFAULT NULL,
  `endometrium_abnormalities` text DEFAULT NULL,
  `right_ovary_measurements` varchar(50) DEFAULT NULL,
  `right_ovary_location` varchar(50) DEFAULT NULL,
  `right_ovary_follicle` varchar(50) DEFAULT NULL,
  `right_ovary_abnormalities` text DEFAULT NULL,
  `left_ovary_measurements` varchar(50) DEFAULT NULL,
  `left_ovary_location` varchar(50) DEFAULT NULL,
  `left_ovary_follicle` varchar(50) DEFAULT NULL,
  `left_ovary_abnormalities` text DEFAULT NULL,
  `cervix_measurements` varchar(50) DEFAULT NULL,
  `nabothian_cyst` varchar(20) DEFAULT NULL,
  `others` text DEFAULT NULL,
  `diagnosis` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci; 