CREATE TABLE hemoglobin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    case_id VARCHAR(255) NOT NULL,
    transaction_id INT NOT NULL,
    hemoglobin DECIMAL(5,2),
    hematocrit DECIMAL(5,2),
    rbc DECIMAL(5,2),
    wbc DECIMAL(5,2),
    neutrophils DECIMAL(5,2),
    lymphocytes DECIMAL(5,2),
    monocytes DECIMAL(5,2),
    eosinophils DECIMAL(5,2),
    basophils DECIMAL(5,2),
    platelet_count DECIMAL(5,2),
    others TEXT,
    remarks TEXT,
    medical_technologist VARCHAR(255),
    pathologist VARCHAR(255),
    report_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES patients(case_id),
    FOREIGN KEY (transaction_id) REFERENCES medical_transactions(transaction_id)
); 